#
# ONYX Epson display controller support
#

obj-$(CONFIG_EPSON_BSAPI)	+= onyx_bsapi.o
obj-$(CONFIG_ONYX_SPLASH)	+= onyx_splash.o

onyx_bsapi-objs				:= bs_cmd.o bs_chip.o
onyx_splash-objs			:= onyx_main.o

